### ISSUE TITLE
内存池设计是否多余

### ISSUE THREAD

**Issue by KKould** [yangyang233333/smallkv#19]
LevelDB中的Arena主要是用于MemTable的，看README内的内存池设计看起来是用于Block的，貌似和Block/Table Cache本身的功能产生了一些冲突？Minor Compaction时生成SSTable时的Block除了最后一个以外都是4k(默认一般考虑4k对齐)的吧，看图总感觉有不少浪费在了小Block上

**Comment by yangyang233333** [comment]
我这个也是用于MemTable的，所以不多余
